name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - production 
      - staging
      - docker_build


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on. Validate build can also run tests if any
    runs-on: ubuntu-latest
    name: Continous Integration
    if: github.ref == 'refs/heads/staging'
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      # - run: npm test
      - run: npm run test:e2e
    
  publish_production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: [build]
     # Steps represent a sequence of tasks that will be executed as part of the job
    if: github.ref == 'refs/heads/production'
    steps:     
      - name: Git setup
        uses: actions/checkout@v2
      
      - name: Dotnet run
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0' # SDK Version to use; x will use the latest version of the 3.1 channel
      
      - name: Publish production
        run: dotnet publish -r linux-x64 -c "Release" -o ./site;

      - name: Generate deployment package 
        run: cd bin/Release/net5.0/linux-x64/; zip ./../../../../publish${{ github.run_id }}.zip *;

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: blogapp-Application
          environment_name: blogapp-env
          version_label: blogapp-${{ github.run_id }}
          region: us-east-2
          deployment_package: publish${{ github.run_id }}.zip

  publish_staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: [build]
     # Steps represent a sequence of tasks that will be executed as part of the job
    if: github.ref == 'refs/heads/staging'
    steps:     
      - name: Git setup
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Nest Build
        run: npm i; npm run build;rm -rf node_modules/;

      - name: Generate deployment package 
        run: zip -r publish${{ github.run_id }}.zip *;

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: auxillo
          environment_name: Auxillo-env
          version_label: auxillo-${{ github.run_id }}
          region: us-east-2
          deployment_package: publish${{ github.run_id }}.zip

  docker_build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/docker_build'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG }}